title: My Tech Blog
email: your-email@example.com
description: >-
  A collection of thoughts, tutorials, and experiences in software development
  and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  yourusername

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
